version: '3.8'

services:
  hello-service:
    build:
      context: ./hello-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3001:3000"     # Cambiado de 3000:3000 a 3001:3000
    volumes:
      - ./hello-service:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  hello-app:
    build:
      context: ./hello-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"       # Cambiado de 80:80 a 8080:80
    volumes:
      - ./hello-app/html:/usr/share/nginx/html
      - ./hello-app/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hello-app/proxy_params:/etc/nginx/proxy_params:ro
    depends_on:
      - hello-service
    restart: unless-stopped