version: '3.8'

services:
  hello-service:
    build:
      context: ./hello-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./hello-service:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - dokploy-network

  hello-app:
    build:
      context: ./hello-app
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL=http://hello-service:3000/api
    ports:
      - "80:80"
    volumes:
      - ./hello-app/html:/usr/share/nginx/html
      - ./hello-app/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hello-app/proxy_params:/etc/nginx/proxy_params:ro
    depends_on:
      - hello-service
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true