# hello-service/Dockerfile

# Etapa de construcción
FROM node:20-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json ./          
RUN npm install --omit=dev     

# Etapa de producción
FROM node:20-alpine            
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY . .                       
EXPOSE 3000                    
CMD ["npm", "start"]           