apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\bin\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: hello-app
  name: hello-app
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: hello-app
