apiVersion: v1
data:
  nginx.conf: |-
    worker_processes auto;  # Cambio a auto para mejor escalabilidad

    events {
        worker_connections 2048;  # Aumentado para mejor rendimiento
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        # Logging settings
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        # Configuración optimizada para Kubernetes
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;

        # Gzip compression
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        # Server block
        server {
            listen 80;
            server_name _;  # Cambiado para aceptar cualquier nombre de dominio

            # Proxy settings for API requests
            location /api/ {
                # Usando el nombre del servicio de Kubernetes
                proxy_pass http://hello-service.default.svc.cluster.local:3000/;
                include /etc/nginx/proxy_params;
            }

            # Static file serving
            location / {
                try_files $uri $uri/ /index.html;
            }

            # Error pages
            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
        }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: hello-app
  name: hello-app-cm1
